baseURL = "https://antonz.org/"
languageCode = "en-us"
title = "Anton Zhiyanov"
theme = "antonz"

enableRobotsTXT = true
rssLimit = 10

[permalinks]
posts = "/:slug"
years = "/:year"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "xcode"

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"

[mediaTypes."application/rss+xml"]
suffixes = [ ]

[params]
author = "Anton Zhiyanov"
description = "Everything about SQLite, Python, open data and awesome software."
